// pages/about.tsx
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Accordion, Card, Col, Row } from 'react-bootstrap';
import { getCurrentStats, Stat } from '../libs/db/stats.ts';
import { mightFailWithArray } from '../libs/utils/util';
import GallMeMaybe from '../public/images/gallmemaybe.jpg';

type Props = {
    stats: Stat[];
    genTime: string;
};

const About = ({ stats, genTime }: Props): JSX.Element => {
    const statMap = new Map(stats.map((s) => [s.type, s.count] as [string, number]));
    return (
        <div className="p-4">
            <Head>
                <title>About Gallformers</title>
                <meta name="description" content="About the creators of gallformers and why we built the site." />
            </Head>

            <Row>
                <Col>
                    <h2>About Us</h2>
                </Col>
            </Row>
            <Row>
                <Col>
                    <p>
                        Gallformers is the product of curious amateurs becoming obsessed. If you are here then you too have at
                        least been touched, if not bitten, by the gall bug. It grows in you, but it is not a{' '}
                        <a href="./glossary#parasitism">parasite</a> nor an <a href="./glossary/#inquiline">inquiline</a>.
                    </p>
                    <p>
                        While you are here we hope that we can help you both ID an unknown plant gall as well as to learn about
                        galls. Whether your interests are very casual, you are a burgeoning scientist, or even a full-fledged{' '}
                        <a href="./glossary#cecidiology">cecidiologist</a> we strive to provide useful tools.
                    </p>
                    <p>
                        This site is open source and you can view the all of the code/data and if so inclined even open a pull
                        request on <a href="https://github.com/jeffdc/gallformers">GitHub</a>. Any and all help is greatly
                        appreciated!
                    </p>
                    <p>
                        We have a{' '}
                        <a href="https://www.patreon.com/gallformers" target="__blank" rel="noreferrer">
                            Patreon
                        </a>{' '}
                        account where you can donate to help cover the costs of building and operating the site.
                    </p>
                </Col>
            </Row>
            <Row>
                <Col>
                    <h4>Contacting Us</h4>
                    <p>
                        You can contact us at <a href="mailto:gallformers@gmail.com">gallformers@gmail.com</a> or{' '}
                        <a href="https://twitter.com/gallformers" target="_blank" rel="noreferrer">
                            @gallformers
                        </a>{' '}
                        on Twitter.
                    </p>
                </Col>
            </Row>
            <Row>
                <h4>Our Co-founders</h4>
                <Col className="pb-3">
                    <Card>
                        <Card.Body className="small">
                            <Card.Title>Adam Kranz</Card.Title>
                            <Card.Text>
                                Adam is an independent ecologist focused on gall inducing organisms in North America. He
                                co-founded Gallformers.org as a community resource to help naturalists identify gall observations
                                and to collect information on undescribed galls. His primary focus is on adding literature and
                                information to the Gallformers database.
                            </Card.Text>
                        </Card.Body>
                        <Card.Footer>
                            <Card.Link href="https://www.inaturalist.org/people/megachile" target="_blank" rel="noreferrer">
                                iNaturalist
                            </Card.Link>
                            <Card.Link href="https://twitter.com/adam_kranz" target="_blank" rel="noreferrer">
                                Twitter
                            </Card.Link>
                        </Card.Footer>
                    </Card>
                </Col>
                <Col>
                    <Card>
                        <Card.Body className="small">
                            <Card.Title>Jeff Clark</Card.Title>
                            <Card.Text>
                                Jeff is a Software Engineer who stumbled upon galls and became obsessed. So much so that he
                                co-founded this site, wrote all the code for this site, and is responsible for keeping it going,
                                fixing it, and implementing new features, and paying the bills. If the site is broken, it is most
                                likely his fault. He is also way too into Oaks and will (HOPEFULLY) soon start building an ID tool
                                for them.
                            </Card.Text>
                        </Card.Body>
                        <Card.Footer>
                            <Card.Link href="https://www.inaturalist.org/people/jeffdc" target="_blank" rel="noreferrer">
                                iNaturalist
                            </Card.Link>
                            <Card.Link href="https://mastodon.social/@jeffdc" target="_blank" rel="noreferrer">
                                Mastodon
                            </Card.Link>
                        </Card.Footer>
                    </Card>
                </Col>
            </Row>
            <Row className="pb-2">
                <a id="administrators">
                    <h4>Administrators</h4>
                </a>
                <Col>
                    We also have an ever growing list of people that help us out as site administrators, without who the site
                    would be far poorer. If you are interested in becoming an administrator{' '}
                    <a href="mailto:gallformers@gmail.com">reach out</a>:
                </Col>
            </Row>
            <Row className="pb-2">
                <Col>
                    <ul>
                        <li>
                            <a href="https://www.inaturalist.org/people/joshuacde">Joshua C&apos;deBaca</a>
                        </li>
                        <li>
                            <a href="https://www.inaturalist.org/people/calconey">Tim Frey</a>
                        </li>
                        <li>
                            <a href="https://www.inaturalist.org/people/kemper">Yann Kemper</a>
                        </li>
                    </ul>
                </Col>
                <Col>
                    <ul>
                        <li>
                            <a href="https://www.inaturalist.org/people/kimberlietx">Kimberlie Sasan</a>
                        </li>
                        <li>
                            <a href="https://www.inaturalist.org/people/73819">Ramsey Sullivan</a>
                        </li>
                    </ul>
                </Col>
            </Row>
            <Row>
                <Col>
                    <h4>Current Site Stats:</h4>
                    As of <em>{genTime}</em> there are:
                    <ul>
                        <li>
                            {statMap.get('galls')} gallformers across {statMap.get('gall-family')} families and{' '}
                            {statMap.get('gall-genera')} genera, of which {statMap.get('undescribed')} are undescribed
                        </li>
                        <li>
                            {statMap.get('hosts')} hosts across {statMap.get('host-family')} families and{' '}
                            {statMap.get('host-genera')} genera
                        </li>
                        <li>{statMap.get('sources')} sources</li>
                    </ul>
                </Col>
            </Row>
            <Row>
                <Col>
                    <h4>Funding</h4>
                    <div className="d-flex align-items-center">
                        <div className="me-1">
                            <a href="https://www.nsf.gov" target="_blank" rel="noreferrer">
                                <Image
                                    src="/images/nsf-logo.svg"
                                    alt="National Science Foundation Logo"
                                    width={200}
                                    height={200}
                                />
                            </a>
                        </div>
                        <p className="mb-0">
                            This site is supported in part by the National Science Foundation under{' '}
                            <a
                                href="https://www.nsf.gov/awardsearch/showAward?AWD_ID=2418250&HistoricalAwards=false"
                                target="_blank"
                                rel="noreferrer"
                            >
                                Grant No. 2418250
                            </a>
                            .
                        </p>
                    </div>
                </Col>
            </Row>
            <Row>
                <Col>
                    <h4>Citing Gallformers</h4>
                    <p>
                        All of our original content is released under a{' '}
                        <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">
                            CC-BY
                        </a>{' '}
                        license.
                    </p>
                    <p>
                        Gallformers would be impossible without the many contributions from the scientific literature as well as
                        the many individuals that have allowed usage of their wonderful photos. We have made every effort to
                        verify and document the license for all content that we use. If you find anything that you think is
                        incorrect please contact us: <a href="mailto:gallformers@gmail.com">Email</a> or{' '}
                        <a href="https://twitter.com/gallformers" target="_blank" rel="noreferrer">
                            Twitter
                        </a>
                    </p>
                    <p>
                        If you are interested in using information on Gallformers in your own research please do. All we ask is
                        that you cite Gallformers and that if you are using any content that is not original to Gallformers that
                        you please cite the original source. When applicable, please cite the specific ID Notes containing the
                        claim being cited.
                    </p>
                    <h5>Citation</h5>
                    <span>
                        <div className="citation">
                            "Gallformers Contributors." Www.gallformers.org, www.gallformers.org. Accessed [date]‌
                        </div>
                        <div className="citation">
                            "Gallformers Contributors." &ldquo;[<i>Species name</i>]&rdquo; Notes on ID and Taxonomy,
                            Www.gallformers.org/[url to specific species], www.gallformers.org. Accessed [date]‌
                        </div>
                    </span>
                </Col>
            </Row>
            <Row className="mt-1 pt-1">
                <Col className="mt-5 pt-5 text-right">
                    <pre className="font-weight-light small text-muted">Build: {process.env.BUILD_ID}</pre>
                </Col>
            </Row>
            <Row>
                <Col>
                    <Accordion>
                        <Accordion.Item eventKey="0">
                            <Accordion.Header>Dare You Click?</Accordion.Header>
                            <Accordion.Body>
                                <Card.Body className="d-flex justify-content-center">
                                    <Image src={GallMeMaybe} alt="Gall Me Maybe" width="300" height="532" />
                                </Card.Body>
                            </Accordion.Body>
                        </Accordion.Item>
                    </Accordion>
                </Col>
            </Row>
        </div>
    );
};

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            stats: await mightFailWithArray<Stat>()(getCurrentStats()),
            genTime: new Date().toUTCString(),
        },
        revalidate: 5 * 60, // every 5 minutes
    };
};

export default About;

// v2/web/src/routes/about/+page.svelte
<script>
	import { onMount } from 'svelte';

	let stats = $state(null);
	let statsLoading = $state(true);
	let genTime = new Date().toUTCString();
	let showEasterEgg = $state(false);

	onMount(async () => {
		try {
			// TODO: Fetch stats from API when endpoint is available
			// For now, we'll show placeholder data
			stats = {
				galls: '~3700',
				gallFamilies: '~17',
				gallGenera: '~470',
				undescribed: '~800',
				hosts: '~2100',
				hostFamilies: '~50',
				hostGenera: '~200',
				sources: '~1200'
			};
		} finally {
			statsLoading = false;
		}
	});
</script>

<svelte:head>
	<title>About Gallformers</title>
	<meta name="description" content="About the creators of gallformers and why we built the site." />
</svelte:head>

<div class="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
	<h1 class="text-3xl font-bold text-gf-maroon mb-8">About Us</h1>

	<div class="prose prose-lg max-w-none">
		<p class="text-gray-700 mb-4">
			Gallformers is the product of curious amateurs becoming obsessed. If you are here then you too have at
			least been touched, if not bitten, by the gall bug. It grows in you, but it is not a
			<a href="/glossary#parasitism" class="text-gf-maroon hover:text-gf-maroon-dark">parasite</a> nor an
			<a href="/glossary#inquiline" class="text-gf-maroon hover:text-gf-maroon-dark">inquiline</a>.
		</p>
		<p class="text-gray-700 mb-4">
			While you are here we hope that we can help you both ID an unknown plant gall as well as to learn about
			galls. Whether your interests are very casual, you are a burgeoning scientist, or even a full-fledged
			<a href="/glossary#cecidiology" class="text-gf-maroon hover:text-gf-maroon-dark">cecidiologist</a> we strive to provide useful tools.
		</p>
		<p class="text-gray-700 mb-4">
			This site is open source and you can view the all of the code/data and if so inclined even open a pull
			request on <a href="https://github.com/jeffdc/gallformers" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">GitHub</a>.
			Any and all help is greatly appreciated!
		</p>
		<p class="text-gray-700 mb-6">
			We have a
			<a href="https://www.patreon.com/gallformers" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Patreon</a>
			account where you can donate to help cover the costs of building and operating the site.
		</p>

		<h2 class="text-2xl font-semibold text-gray-800 mt-8 mb-4">Contacting Us</h2>
		<p class="text-gray-700 mb-6">
			You can contact us at <a href="mailto:gallformers@gmail.com" class="text-gf-maroon hover:text-gf-maroon-dark">gallformers@gmail.com</a> or
			<a href="https://twitter.com/gallformers" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">@gallformers</a>
			on Twitter.
		</p>

		<h2 class="text-2xl font-semibold text-gray-800 mt-8 mb-4">Our Co-founders</h2>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
			<div class="bg-white rounded-lg shadow-md p-6">
				<h3 class="text-lg font-semibold text-gray-800 mb-2">Adam Kranz</h3>
				<p class="text-gray-600 text-sm mb-4">
					Adam is an independent ecologist focused on gall inducing organisms in North America. He
					co-founded Gallformers.org as a community resource to help naturalists identify gall observations
					and to collect information on undescribed galls. His primary focus is on adding literature and
					information to the Gallformers database.
				</p>
				<div class="flex gap-4 text-sm">
					<a href="https://www.inaturalist.org/people/megachile" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">iNaturalist</a>
					<a href="https://twitter.com/adam_kranz" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Twitter</a>
				</div>
			</div>
			<div class="bg-white rounded-lg shadow-md p-6">
				<h3 class="text-lg font-semibold text-gray-800 mb-2">Jeff Clark</h3>
				<p class="text-gray-600 text-sm mb-4">
					Jeff is a Software Engineer who stumbled upon galls and became obsessed. So much so that he
					co-founded this site, wrote all the code for this site, and is responsible for keeping it going,
					fixing it, and implementing new features, and paying the bills. If the site is broken, it is most
					likely his fault. He is also way too into Oaks and will (HOPEFULLY) soon start building an ID tool
					for them.
				</p>
				<div class="flex gap-4 text-sm">
					<a href="https://www.inaturalist.org/people/jeffdc" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">iNaturalist</a>
					<a href="https://mastodon.social/@jeffdc" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Mastodon</a>
				</div>
			</div>
		</div>

		<h2 id="administrators" class="text-2xl font-semibold text-gray-800 mt-8 mb-4">Administrators</h2>
		<p class="text-gray-700 mb-4">
			We also have an ever growing list of people that help us out as site administrators, without whom the site
			would be far poorer. If you are interested in becoming an administrator
			<a href="mailto:gallformers@gmail.com" class="text-gf-maroon hover:text-gf-maroon-dark">reach out</a>:
		</p>
		<div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
			<ul class="list-disc list-inside text-gray-700">
				<li><a href="https://www.inaturalist.org/people/joshuacde" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Joshua C'deBaca</a></li>
				<li><a href="https://www.inaturalist.org/people/calconey" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Tim Frey</a></li>
				<li><a href="https://www.inaturalist.org/people/kemper" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Yann Kemper</a></li>
			</ul>
			<ul class="list-disc list-inside text-gray-700">
				<li><a href="https://www.inaturalist.org/people/kimberlietx" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Kimberlie Sasan</a></li>
				<li><a href="https://www.inaturalist.org/people/73819" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Ramsey Sullivan</a></li>
			</ul>
		</div>

		<h2 class="text-2xl font-semibold text-gray-800 mt-8 mb-4">Current Site Stats</h2>
		{#if statsLoading}
			<p class="text-gray-600">Loading stats...</p>
		{:else if stats}
			<p class="text-gray-700 mb-2">As of <em>{genTime}</em> there are:</p>
			<ul class="list-disc list-inside text-gray-700 mb-6">
				<li>
					{stats.galls} gallformers across {stats.gallFamilies} families and {stats.gallGenera} genera,
					of which {stats.undescribed} are undescribed
				</li>
				<li>
					{stats.hosts} hosts across {stats.hostFamilies} families and {stats.hostGenera} genera
				</li>
				<li>{stats.sources} sources</li>
			</ul>
		{/if}

		<h2 class="text-2xl font-semibold text-gray-800 mt-8 mb-4">Funding</h2>
		<div class="flex items-center gap-4 mb-6">
			<a href="https://www.nsf.gov" target="_blank" rel="noreferrer">
				<img src="/images/nsf-logo.svg" alt="National Science Foundation Logo" class="w-32 h-32" />
			</a>
			<p class="text-gray-700">
				This site is supported in part by the National Science Foundation under
				<a href="https://www.nsf.gov/awardsearch/showAward?AWD_ID=2418250&HistoricalAwards=false" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">
					Grant No. 2418250
				</a>.
			</p>
		</div>

		<h2 class="text-2xl font-semibold text-gray-800 mt-8 mb-4">Citing Gallformers</h2>
		<p class="text-gray-700 mb-4">
			All of our original content is released under a
			<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">CC-BY</a>
			license.
		</p>
		<p class="text-gray-700 mb-4">
			Gallformers would be impossible without the many contributions from the scientific literature as well as
			the many individuals that have allowed usage of their wonderful photos. We have made every effort to
			verify and document the license for all content that we use. If you find anything that you think is
			incorrect please contact us: <a href="mailto:gallformers@gmail.com" class="text-gf-maroon hover:text-gf-maroon-dark">Email</a> or
			<a href="https://twitter.com/gallformers" target="_blank" rel="noreferrer" class="text-gf-maroon hover:text-gf-maroon-dark">Twitter</a>.
		</p>
		<p class="text-gray-700 mb-4">
			If you are interested in using information on Gallformers in your own research please do. All we ask is
			that you cite Gallformers and that if you are using any content that is not original to Gallformers that
			you please cite the original source. When applicable, please cite the specific ID Notes containing the
			claim being cited.
		</p>

		<h3 class="text-lg font-semibold text-gray-800 mt-6 mb-2">Citation</h3>
		<div class="bg-gray-50 p-4 rounded-lg font-mono text-sm text-gray-700 mb-2">
			"Gallformers Contributors." Www.gallformers.org, www.gallformers.org. Accessed [date]
		</div>
		<div class="bg-gray-50 p-4 rounded-lg font-mono text-sm text-gray-700 mb-8">
			"Gallformers Contributors." "[<em>Species name</em>]" Notes on ID and Taxonomy,
			Www.gallformers.org/[url to specific species], www.gallformers.org. Accessed [date]
		</div>

		<!-- Easter Egg -->
		<div class="mt-12 border-t pt-6">
			<button
				onclick={() => showEasterEgg = !showEasterEgg}
				class="text-gray-500 hover:text-gray-700 text-sm"
			>
				{showEasterEgg ? 'Hide' : 'Dare You Click?'}
			</button>
			{#if showEasterEgg}
				<div class="mt-4 flex justify-center">
					<img src="/images/gallmemaybe.jpg" alt="Gall Me Maybe" class="max-w-xs rounded-lg shadow-lg" />
				</div>
			{/if}
		</div>
	</div>
</div>
