// v2/web/src/routes/gall/[id]/+page.svelte
<script>
	import { toast } from '$lib/components';
	import { RangeMap } from '$lib/components';
	import ImageGallery from '$lib/components/public/ImageGallery.svelte';
	import SourceList from '$lib/components/public/SourceList.svelte';
	import ExternalLinks from '$lib/components/public/ExternalLinks.svelte';
	import TaxonomyBreadcrumb from '$lib/components/public/TaxonomyBreadcrumb.svelte';
	import SpeciesSynonymy from '$lib/components/public/SpeciesSynonymy.svelte';
	import DataCompletenessIndicator from '$lib/components/public/DataCompletenessIndicator.svelte';
	import EditButton from '$lib/components/public/EditButton.svelte';
	import InfoTip from '$lib/components/public/InfoTip.svelte';
	import ErrorMessage from '$lib/components/public/ErrorMessage.svelte';

	let { data } = $props();

	// Selected source state
	let selectedSourceId = $state(data.defaultSourceId);

	// Detachable value mapping
	const detachableValues = {
		0: 'Integral',
		1: 'Detachable',
		2: 'Both'
	};

	/**
	 * Get display value for detachable field
	 */
	function getDetachableDisplay(value) {
		if (value === null || value === undefined) return '';
		return detachableValues[value] || '';
	}

	/**
	 * Check if detachable is "Both"
	 */
	function isDetachableBoth(value) {
		return value === 2;
	}

	/**
	 * Format filter fields (colors, shapes, etc.) for display
	 */
	function formatFields(fields) {
		if (!fields || fields.length === 0) return '';
		return fields.map((f) => f.field).join(', ');
	}

	/**
	 * Copy gallformers code to clipboard for undescribed species
	 */
	async function copyGallformersCode() {
		if (!data.gall || !data.taxonomy) return;

		// Extract code: remove genus name and any trailing parenthetical
		const code = data.gall.name
			.replace(data.taxonomy.genus?.name || '', '')
			.trim()
			.replace(/ \([^)]+\)$/, '');

		try {
			await navigator.clipboard.writeText(code);
			toast.success('Code copied to clipboard');
		} catch (err) {
			console.error('Failed to copy:', err);
			toast.error('Failed to copy code');
		}
	}

	/**
	 * Get completeness level based on datacomplete flag
	 */
	function getCompletenessLevel(datacomplete) {
		return datacomplete ? 'complete' : 'unknown';
	}
</script>

<svelte:head>
	{#if data.gall}
		<title>{data.gall.name} | Gallformers</title>
		<meta
			name="description"
			content="{data.gall.name} - A gall species on Gallformers. {data.gall.undescribed
				? 'The inducer of this gall is unknown or undescribed.'
				: ''}"
		/>
	{:else}
		<title>Gall Not Found | Gallformers</title>
	{/if}
</svelte:head>

<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
	{#if data.error}
		<ErrorMessage message={data.error} />
	{:else if data.gall}
		<!-- Phenology Tool Link -->
		<div class="mb-4 text-center">
			<a
				href="https://megachile.shinyapps.io/doycalc/"
				target="_blank"
				rel="noreferrer"
				class="text-sm text-gf-maroon hover:underline"
			>
				<span class="hidden md:inline">
					Explore the seasonal timing of gall development and emergence with our phenology tool
				</span>
				<span class="md:hidden" title="Explore the seasonal timing of gall development and emergence with our phenology tool">
					Phenology Tool
				</span>
			</a>
		</div>

		<!-- Main Content Grid -->
		<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
			<!-- Left Column: Details -->
			<div class="lg:col-span-2 space-y-6">
				<!-- Header: Name + Status -->
				<div class="flex items-start justify-between gap-4">
					<div class="flex-1">
						<h1 class="text-2xl font-bold text-gf-maroon">
							<em>{data.gall.name}</em>
						</h1>
					</div>
					<div class="flex items-center gap-2">
						<EditButton id={data.gall.id} type="gall" />
						<DataCompletenessIndicator
							level={getCompletenessLevel(data.gall.datacomplete)}
							showLabel={false}
						/>
					</div>
				</div>

				<!-- Undescribed Warning -->
				{#if data.gall.undescribed}
					<div class="bg-red-50 border border-red-200 rounded-md p-4">
						<div class="flex flex-wrap items-center gap-3">
							<span class="text-red-700">
								The inducer of this gall is unknown or undescribed.
							</span>
							<button
								type="button"
								onclick={copyGallformersCode}
								class="px-3 py-1 text-sm border border-gray-300 rounded-md bg-white hover:bg-gray-50 text-gray-700 transition-colors"
							>
								Copy gallformers code
							</button>
						</div>
					</div>
				{/if}

				<!-- Taxonomy Breadcrumb -->
				{#if data.taxonomy}
					<TaxonomyBreadcrumb
						family={data.taxonomy.family}
						genus={data.taxonomy.genus}
						section={data.taxonomy.section}
						showSection={!!data.taxonomy.section}
					/>
				{/if}

				<!-- Hosts -->
				{#if data.gall.hosts && data.gall.hosts.length > 0}
					<div>
						<span class="font-semibold">Hosts: </span>
						<em>
							{#each data.gall.hosts as host, i}
								<a href="/host/{host.id}" class="text-blue-600 hover:underline">
									{host.name}
								</a>{i < data.gall.hosts.length - 1 ? ' / ' : ''}
							{/each}
						</em>
						<EditButton id={data.gall.id} type="gallhost" />
					</div>
				{/if}

				<!-- Morphological Characteristics -->
				<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
					<!-- Column 1 -->
					<div class="space-y-2">
						<div>
							<span class="font-semibold">Detachable: </span>
							<span>{getDetachableDisplay(data.gall.detachable)}</span>
							{#if isDetachableBoth(data.gall.detachable)}
								<InfoTip text="This gall can be both detachable and integral depending on what stage of its lifecycle it is in." />
							{/if}
						</div>
						<div>
							<span class="font-semibold">Color: </span>
							<span>{formatFields(data.gall.colors)}</span>
						</div>
						<div>
							<span class="font-semibold">Texture: </span>
							<span>{formatFields(data.gall.textures)}</span>
						</div>
						<div>
							<span class="font-semibold">Shape: </span>
							<span>{formatFields(data.gall.shapes)}</span>
						</div>
						<div>
							<span class="font-semibold">Season: </span>
							<span>{formatFields(data.gall.seasons)}</span>
						</div>
					</div>

					<!-- Column 2 -->
					<div class="space-y-2">
						<div>
							<span class="font-semibold">Alignment: </span>
							<span>{formatFields(data.gall.alignments)}</span>
						</div>
						<div>
							<span class="font-semibold">Walls: </span>
							<span>{formatFields(data.gall.walls)}</span>
						</div>
						<div>
							<span class="font-semibold">Location: </span>
							<span>{formatFields(data.gall.locations)}</span>
						</div>
						<div>
							<span class="font-semibold">Form: </span>
							<span>{formatFields(data.gall.forms)}</span>
						</div>
						<div>
							<span class="font-semibold">Cells: </span>
							<span>{formatFields(data.gall.cells)}</span>
						</div>
					</div>
				</div>

				<!-- Range Map -->
				{#if data.range && data.range.size > 0}
					<div>
						<div class="flex items-center gap-1 mb-2">
							<span class="font-semibold">Possible Range:</span>
							<InfoTip text="The gall's range is computed from the range of all hosts that the gall occurs on. In some cases we have evidence that the gall does not occur across the full range of the hosts and we will remove these places from the range. For undescribed species we will show the expected range based on hosts plus where the galls have been observed. All of this said, the exact ranges for most galls is uncertain." />
						</div>
						<div class="max-w-md">
							<RangeMap inRange={data.range} excludedRange={data.excludedRange} />
						</div>
					</div>
				{/if}

				<!-- Aliases/Synonymy -->
				{#if data.gall.aliases && data.gall.aliases.length > 0}
					<SpeciesSynonymy aliases={data.gall.aliases} showAllByDefault={true} />
				{/if}
			</div>

			<!-- Right Column: Images -->
			<div class="lg:col-span-1">
				<ImageGallery images={data.images} />
			</div>
		</div>

		<!-- Sources Section -->
		<div class="mt-8">
			<hr class="border-gray-200 mb-6" />
			{#if data.sources && data.sources.length > 0}
				<SourceList sources={data.sources} bind:selectedId={selectedSourceId} />
			{:else}
				<p class="text-gray-500">No sources available for this species.</p>
			{/if}
		</div>

		<!-- External Links Section -->
		<div class="mt-8">
			<hr class="border-gray-200 mb-6" />
			<div class="flex items-center gap-2 mb-4">
				<span class="font-semibold">See Also:</span>
			</div>
			<ExternalLinks name={data.gall.name} undescribed={data.gall.undescribed} />
		</div>
	{:else}
		<ErrorMessage message="Gall not found" />
	{/if}
</div>

// pages/gall/[id]/index.tsx
import * as O from 'fp-ts/lib/Option';
import { constant, pipe } from 'fp-ts/lib/function';
import { GetStaticPaths, GetStaticProps } from 'next';
import ErrorPage from 'next/error.js';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { Button, Col, Container, OverlayTrigger, Row, Tooltip } from 'react-bootstrap';
import toast, { Toaster } from 'react-hot-toast';
import Edit from '../../../components/edit';
import Images from '../../../components/images';
import InfoTip from '../../../components/infotip';
import RangeMap from '../../../components/rangemap';
import SeeAlso from '../../../components/seealso';
import SourceList from '../../../components/sourcelist';
import SpeciesSynonymy from '../../../components/speciesSynonymy';
import { DetachableBoth, FGS, GallApi, GallHost, SimpleSpecies, TaxonCodeValues } from '../../../libs/api/apitypes';
import { allGallIds, gallById, getRelatedGalls } from '../../../libs/db/gall';
import { taxonomyForSpecies } from '../../../libs/db/taxonomy';
import { linkSourceToGlossary } from '../../../libs/pages/glossary.ts';
import { getStaticPathsFromIds, getStaticPropsWith, getStaticPropsWithContext } from '../../../libs/pages/nextPageHelpers';
import { createSummaryGall, defaultSource, formatWithDescription } from '../../../libs/pages/renderhelpers';

type Props = {
    species: GallApi;
    taxonomy: FGS;
    relatedGalls: SimpleSpecies[];
};

// eslint-disable-next-line react/display-name
const hostAsLink = (len: number) => (h: GallHost, idx: number) => {
    return (
        <span key={h.id}>
            <Link href={`/host/${h.id}`}>{h.name}</Link>
            {idx < len - 1 ? ' / ' : ''}
        </span>
    );
};

const Gall = ({ species, taxonomy, relatedGalls }: Props): JSX.Element => {
    const router = useRouter();
    const defSource = defaultSource(species?.speciessource, router.query.source);
    const [selectedSource, setSelectedSource] = useState(defSource);

    const range = new Set<string>();
    species?.hosts.flatMap((gh) => gh.places.forEach((p) => range.add(p.code)));
    species?.excludedPlaces.forEach((p) => range.delete(p.code));

    // If the page is not yet generated, this will be displayed initially until getStaticProps() finishes running
    if (router.isFallback) {
        return <div>Loading...</div>;
    } else if (species == null) {
        return <ErrorPage statusCode={404} />;
    }

    // the hosts will not be sorted, so sort them for display
    species.hosts.sort((a, b) => a.name.localeCompare(b.name));
    const hostLinker = hostAsLink(species.hosts.length);

    const copyGallformersCode = () => {
        const code = species.name
            .replace(taxonomy.genus.name, '')
            .trim()
            .replace(/ \([^)]+\)$/, ''); // Remove trailing parenthetical like " (agamic)"
        void navigator.clipboard.writeText(code).then(() => {
            toast.success('Code copied to clipboard');
        });
    };

    return (
        <Container key={species.id} className="pt-2 fluid">
            <Toaster />
            <Head>
                <title>{species.name}</title>
                <meta name="description" content={`${species.name} - ${createSummaryGall(species)}`} />
            </Head>

            <Row className="mt-0 mb-1">
                <Col>
                    <div className="d-flex justify-content-center">
                        <div className="text-center">
                            <Link
                                href="https://megachile.shinyapps.io/doycalc/"
                                target="_blank"
                                rel="noreferrer"
                                className="text-decoration-underline"
                            >
                                <div className="d-none d-md-block">
                                    <span className="small">
                                        Explore the seasonal timing of gall development and emergence with our phenology tool
                                    </span>
                                </div>
                                <div className="d-md-none">
                                    <span
                                        className="small"
                                        title="Explore the seasonal timing of gall development and emergence with our phenology tool"
                                    >
                                        🗓️ Phenology Tool
                                    </span>
                                </div>
                            </Link>
                        </div>
                    </div>
                </Col>
            </Row>

            <Row className="mt-2">
                {/* Details */}
                <Col sm={12} md={8}>
                    <Row>
                        <Col>
                            <Row>
                                <Col>
                                    <h2>
                                        <em>{species.name}</em>
                                    </h2>
                                </Col>
                                <Col xs={2}>
                                    <span className="p-0 pe-1 my-auto">
                                        <Edit id={species.id} type="gall" />
                                        <OverlayTrigger
                                            placement="right"
                                            overlay={
                                                <Tooltip id="datacomplete">
                                                    {species.datacomplete
                                                        ? 'All sources containing unique information relevant to this gall have been added and are reflected in its associated data. However, filter criteria may not be comprehensive in every field.'
                                                        : 'We are still working on this species so data is missing.'}
                                                </Tooltip>
                                            }
                                        >
                                            <Button variant="outline-light">{species.datacomplete ? '💯' : '❓'}</Button>
                                        </OverlayTrigger>
                                    </span>
                                </Col>
                            </Row>
                            <Row hidden={!species.undescribed}>
                                <Col>
                                    <span className="text-danger">The inducer of this gall is unknown or undescribed.</span>
                                    <Button variant="outline-secondary" size="sm" className="ms-2" onClick={copyGallformersCode}>
                                        Copy gallformers code
                                    </Button>
                                </Col>
                            </Row>
                            <Row>
                                <Col>
                                    <strong>Family: </strong>
                                    <Link key={taxonomy.family.id} href={`/family/${taxonomy.family.id}`}>
                                        {taxonomy.family.name}
                                    </Link>
                                    {' | '}
                                    <strong>Genus: </strong>
                                    <Link key={taxonomy.genus.id} href={`/genus/${taxonomy.genus.id}`}>
                                        {formatWithDescription(taxonomy.genus.name, taxonomy.genus.description)}
                                    </Link>
                                </Col>
                            </Row>
                            <Row className="">
                                <Col>
                                    <strong>Hosts:</strong> <em>{species.hosts.map(hostLinker)}</em>
                                    <Edit id={species.id} type="gallhost" />
                                </Col>
                            </Row>
                            <Row>
                                <Col xs={12} md={6} lg={4}>
                                    <Row>
                                        <Col>
                                            <strong>Detachable:</strong> {species.detachable.value}
                                            {species.detachable.value === DetachableBoth.value && (
                                                <InfoTip
                                                    id="detachable"
                                                    text="This gall can be both detachable and integral depending on what stage of its lifecycle it is in."
                                                />
                                            )}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Color:</strong> {species.color.map((c) => c.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Texture:</strong> {species.texture.map((t) => t.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Abundance:</strong>{' '}
                                            {pipe(
                                                species.abundance,
                                                O.fold(constant(''), (a) => a.abundance),
                                            )}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Shape:</strong> {species.shape.map((s) => s.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Season:</strong> {species.season.map((s) => s.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Related: </strong>
                                            {relatedGalls.map((g, i) => (
                                                <span key={g.id}>
                                                    {' '}
                                                    <Link key={g.id} href={`/gall/${g.id}`}>
                                                        {g.name}
                                                    </Link>
                                                    {i < relatedGalls.length - 1 ? ', ' : ''}
                                                </span>
                                            ))}
                                        </Col>
                                    </Row>
                                </Col>
                                <Col xs={12} md={6} lg={4}>
                                    <Row>
                                        <Col>
                                            <strong>Alignment:</strong> {species.alignment.map((a) => a.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Walls:</strong> {species.walls.map((w) => w.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Location:</strong> {species.location.map((l) => l.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Form:</strong> {species.form.map((s) => s.field).join(', ')}
                                        </Col>
                                    </Row>
                                    <Row>
                                        <Col>
                                            <strong>Cells:</strong> {species.cells.map((s) => s.field).join(', ')}
                                        </Col>
                                    </Row>
                                </Col>
                                <Col xs={12} lg={4} className="p-0 m-0">
                                    <strong>Possible Range:</strong>
                                    <InfoTip
                                        id="rangetip"
                                        text="The gall's range is computed from the range of all hosts that the gall occurs on. In some cases we have evidence that the gall does not occur across the full range of the hosts and we will remove these places from the range. For undescribed species we will show the expected range based on hosts plus where the galls have been observed. All of this said, the exact ranges for most galls is uncertain."
                                    />
                                    <RangeMap range={range} />
                                </Col>
                            </Row>
                        </Col>
                    </Row>
                    <Row>
                        <Col>
                            <SpeciesSynonymy aliases={species.aliases} showAll={true} />
                        </Col>
                    </Row>
                </Col>
                {/* Images */}
                <Col sm={{ span: 12 }} md={4}>
                    <Row>
                        <Col>
                            <Images sp={species} type="gall" />
                        </Col>
                    </Row>
                </Col>
                {/* Description */}
                <Col>
                    <Row>
                        <Col>
                            <hr />
                        </Col>
                    </Row>
                </Col>
            </Row>
            <Row>
                <Col>
                    <SourceList
                        data={species.speciessource}
                        defaultSelection={selectedSource}
                        onSelectionChange={(s) =>
                            setSelectedSource(species.speciessource.find((speciesSource) => speciesSource.source_id == s?.id))
                        }
                        taxonType={TaxonCodeValues.GALL}
                    />
                    <hr />
                    <Row>
                        <Col className="align-self-center">
                            <strong>See Also:</strong>
                        </Col>
                    </Row>
                    <SeeAlso name={species.name} undescribed={species.undescribed} />
                </Col>
            </Row>
        </Container>
    );
};

// Use static so that this stuff can be built once on the server-side and then cached.
export const getStaticProps: GetStaticProps = async (context) => {
    try {
        const g = await getStaticPropsWithContext(context, gallById, 'gall');
        if (!g[0]) throw new Error('404');

        const gall = g[0];
        const sources = gall ? await linkSourceToGlossary(gall.speciessource) : null;
        const fgs = gall ? await getStaticPropsWithContext(context, taxonomyForSpecies, 'taxonomy') : null;
        const relatedGalls = gall ? await getStaticPropsWith<SimpleSpecies>(() => getRelatedGalls(gall), 'related galls') : null;

        return {
            props: {
                species: gall ? { ...gall, speciessource: sources } : null,
                taxonomy: fgs,
                relatedGalls: relatedGalls,
            },
            revalidate: 1,
        };
    } catch {
        return { notFound: true };
    }
};

export const getStaticPaths: GetStaticPaths = async () => getStaticPathsFromIds(allGallIds);

export default Gall;
